name: build-and-release

on:
  # Runs daily at UTC midnight to minimize risk of overstepping
  # manual builds of same date.
  schedule:
    - cron: "0 0 * * *"

  # Allow manual activations.
  workflow_dispatch:

permissions:
  # Allow release creation
  contents: write

env:
  # prevents warnings in the vscode editor.
  RELEASE_TAG: ""
  PACKAGE_TAG: ""
  VSCODE_EXTENSION_VERSION: ""
  APIO_RELEASE_GITHUB_REPO: ""
  APIO_RELEASE_TAG: ""

jobs:
  # ----- Parameters collection job
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: List repo files
        run: |
          ls -al

      # E.g. "2025-11-02"
      - name: Determine release tag
        run: |
          release_tag="$(date +'%Y-%m-%d')"
          echo $release_tag
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

      # E.g. "20251102"
      - name: Determine package tag
        run: |
          package_tag="${RELEASE_TAG//-/}"
          echo $package_tag
          echo "PACKAGE_TAG=$package_tag" >> $GITHUB_ENV

      - name: Determine package file name
        run: |
          package_name="apio-vscode-${PACKAGE_TAG}.vsix"
          echo $package_name
          echo "PACKAGE_NAME=$package_name" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json" # Detects from engines.node

      - name: Verify npx
        run: npx --version

      - name: List repo files
        run: |
          ls -al

      - name: Extract values and set environment variables
        run: |
          const workspace = process.env.GITHUB_WORKSPACE;

          const fs = require('fs');
          const path = require('path');
          const constants = require(path.join(workspace, 'constants.js'));
          const pkg = require(path.join(workspace, 'package.json'));

          const envPath = process.env.GITHUB_ENV;

          fs.appendFileSync(envPath, `VSCODE_EXTENSION_VERSION=${pkg.version}\n`);
          fs.appendFileSync(envPath, `APIO_RELEASE_GITHUB_REPO=${constants.APIO_RELEASE_GITHUB_REPO}\n`);
          fs.appendFileSync(envPath, `APIO_RELEASE_TAG=${constants.APIO_RELEASE_TAG}\n`);
        shell: node {0}

      # Create the build info file that we will include in the package.
      - name: Create build info
        run: |
          # Generate build-info.json
          cat > build-info.json <<EOF
          {
            "package-name":  "apio-vscode",
            "description" : "Apio extension for Visual Studio Code",
            "source-repo":  "${{github.repository}}",
            "source-sha":   "${{ github.sha }}",
            "source-branch: "${{ github.ref_name }}",
            "package-version": "$VSCODE_EXTENSION_VERSION",
            "apio-release-repo": "APIO_RELEASE_GITHUB_REPO",
            "apio-release-tag" : "APIO_RELEASE_TAG",
            "build-time":  "$(date +'%Y-%m-%d %H:%M:%S %Z')",
            "builder-workflow":  "${{ github.workflow }}",
            "workflow-run-id":  "${{github.run_id}}",
            "workflow-run-number": "${{github.run_number}}",
            "release-tag": "${RELEASE_TAG}"
          }
          EOF

          cat -n build-info.json

      - name: Format build info 
        run: |
          set -x
          cat -n build-info.json
          npm install -g json-align
          json-align --in-place --spaces 2 build-info.json
          cat -n build-info.json

      - name: Build the .vsix file
        run: |
          ./scripts/build.sh

      - name: Rename package file
        run: |
          mv apio*.vsix $PACKAGE_NAME
          ls -al

      - name: Show packaged files
        run: |
          unzip -l $PACKAGE_NAME


      # Add notes for the release page.
      - name: Prepare release text
        run: |
          cat  > RELEASE-BODY.txt <<EOF
          This is the daily build of the Apio VSCode extension.

          > This repository keeps only the last 5 pre-releases so to preserve
          > a release, check off its's pre-release [] checkbox.

          Build info:
          \`\`\`
          $(tr -d '",{}' < build-info.json)
          \`\`\`

          Installation instructions](https://fpgawars.github.io/apio/docs/quick-start)
          EOF

          cat -n $out

      # Delete old pre-releases, keeps all releases.
      - name: Delete old pre-releases
        uses: sgpublic/delete-release-action@v1.2
        with:
          # Keep all stable releases .
          release-drop: false
          # Delete old pre-releases, keep the newest 10 (excluding the absolute latest)
          pre-release-drop: true
          pre-release-keep-count: 5
          pre-release-drop-tag: true # Also delete tags of deleted pre-releases
          # Keep all drafts.
          draft-drop: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Delete same tag pre-release if exist.
        run: |
          # Status values:
          #   "false" - exists and is a release exists
          #   "true"  - exists and is a pre-release
          #   ""      - doesn't exist
          status=$(gh release view "$RELEASE_TAG" --json isPrerelease -q .isPrerelease  || true)
          echo "Status is [$status]"
          if [[ "$status" == "false" ]]; then
            echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
            exit 1
          elif [[ "$status" == "true" ]]; then
            echo "Deleting existing pre-release and tag $RELEASE_TAG."
            gh release delete "$RELEASE_TAG" --yes --cleanup-tag
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{env.RELEASE_TAG}}
          name: ${{env.RELEASE_TAG}}
          preserve_order: true
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            apio-vscode-${{env.PACKAGE_TAG}}.vsix
